# Puerto en el que escucha el servidor embebido Tomcat
server.port=8080

# Nombre lógico de la aplicación (usado por Spring Boot Actuator y registros de servicio)
spring.application.name=ms-random-number
