module.exports = {
  generateTests(parentIssueTitle) {
    return [
      `## 🧪 Testing Subagent — JUnit 5`,
      ``,
      `**Skill:** \`java-testing-junit5\` | **Tarea:** \`[Tests]\``,
      ``,
      `He analizado el issue y genero los tests unitarios y de integración. ✅`,
      ``,
      `---`,
      ``,
      `### 📄 \`src/test/java/com/example/msrandomnumber/service/RandomNumberServiceTest.java\``,
      ``,
      '```java',
      `package com.example.msrandomnumber.service;`,
      ``,
      `import org.junit.jupiter.api.Test;`,
      `import org.junit.jupiter.api.extension.ExtendWith;`,
      `import org.mockito.junit.jupiter.MockitoExtension;`,
      ``,
      `import static org.junit.jupiter.api.Assertions.assertTrue;`,
      ``,
      `@ExtendWith(MockitoExtension.class)`,
      `class RandomNumberServiceTest {`,
      ``,
      `    private final RandomNumberService service = new RandomNumberServiceImpl();`,
      ``,
      `    @Test`,
      `    void getRandomNumber_shouldReturnValueBetween1And9() {`,
      `        for (int i = 0; i < 100; i++) {`,
      `            int result = service.getRandomNumber();`,
      `            assertTrue(result >= 1 && result <= 9,`,
      `                "El número debe estar entre 1 y 9 (inclusive), pero fue: " + result);`,
      `        }`,
      `    }`,
      `}`,
      '```',
      ``,
      `---`,
      ``,
      `### 📄 \`src/test/java/com/example/msrandomnumber/controller/RandomNumberControllerTest.java\``,
      ``,
      '```java',
      `package com.example.msrandomnumber.controller;`,
      ``,
      `import org.junit.jupiter.api.Test;`,
      `import org.springframework.beans.factory.annotation.Autowired;`,
      `import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;`,
      `import org.springframework.boot.test.context.SpringBootTest;`,
      `import org.springframework.test.web.servlet.MockMvc;`,
      ``,
      `import static org.hamcrest.Matchers.allOf;`,
      `import static org.hamcrest.Matchers.greaterThanOrEqualTo;`,
      `import static org.hamcrest.Matchers.lessThanOrEqualTo;`,
      `import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;`,
      `import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;`,
      `import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;`,
      ``,
      `@SpringBootTest`,
      `@AutoConfigureMockMvc`,
      `class RandomNumberControllerTest {`,
      ``,
      `    @Autowired`,
      `    private MockMvc mockMvc;`,
      ``,
      `    @Test`,
      `    void getRandom_shouldReturn200WithNumberBetween1And9() throws Exception {`,
      `        mockMvc.perform(get("/api/random"))`,
      `            .andExpect(status().isOk())`,
      `            .andExpect(jsonPath("$.number").exists())`,
      `            .andExpect(jsonPath("$.number").value(`,
      `                allOf(greaterThanOrEqualTo(1), lessThanOrEqualTo(9))`,
      `            ));`,
      `    }`,
      `}`,
      '```',
      ``,
      `---`,
      ``,
      `> 🤖 Generado automáticamente por el **testing-subagent** con skill \`java-testing-junit5\``,
    ].join('\n');
  },
};
