module.exports = {
  generateReadme(parentIssueTitle) {
    const title = parentIssueTitle || 'Microservicio Random Number';

    const readmeContent = [
      `# ms-random-number`,
      ``,
      `Microservicio Spring Boot que expone un endpoint REST para obtener un número aleatorio entre 1 y 9.`,
      ``,
      `## Tecnologías`,
      ``,
      `- Java 17`,
      `- Spring Boot 3.x`,
      `- Maven`,
      ``,
      `## Endpoint`,
      ``,
      `\`\`\``,
      `GET /api/random`,
      `Response: {"number": N}  donde N es un entero entre 1 y 9`,
      `\`\`\``,
      ``,
      `## Cómo ejecutar`,
      ``,
      `\`\`\`bash`,
      `./mvnw spring-boot:run`,
      `\`\`\``,
      ``,
      `## Ejemplo con curl`,
      ``,
      `\`\`\`bash`,
      `curl http://localhost:8080/api/random`,
      `# {"number": 7}`,
      `\`\`\``,
      ``,
      `## Tests`,
      ``,
      `\`\`\`bash`,
      `./mvnw test`,
      `\`\`\``,
    ].join('\n');

    return [
      `## 📄 Docs Subagent — Technical Documentation`,
      ``,
      `**Skill:** \`technical-documentation\` | **Tarea:** \`[Docs]\``,
      ``,
      `He analizado el issue y genero la documentación del microservicio. 📝`,
      ``,
      title !== 'Microservicio Random Number' ? `> 📌 Issue padre: ${title}` : '',
      ``,
      `---`,
      ``,
      `### 📄 \`README.md\``,
      ``,
      '```markdown',
      readmeContent,
      '```',
      ``,
      `---`,
      ``,
      `> 🤖 Generado automáticamente por el **docs-subagent** con skill \`technical-documentation\``,
    ].join('\n');
  },
};
